### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by cxm1995** [Cw-zero/TensorRT_yolo3#5]
Layer of type yolo not supported, skipping ONNX node generation.
Layer of type yolo not supported, skipping ONNX node generation.
Layer of type yolo not supported, skipping ONNX node generation.
Traceback (most recent call last):
  File "yolov3_to_onnx.py", line 672, in <module>
    main()
  File "yolov3_to_onnx.py", line 660, in main
    verbose=True)
  File "yolov3_to_onnx.py", line 350, in build_onnx_graph
    conv_params)
  File "yolov3_to_onnx.py", line 212, in load_conv_weights
    conv_params, 'bn', 'bias')
  File "yolov3_to_onnx.py", line 261, in _create_param_tensors
    param_name, TensorProto.FLOAT, param_data_shape, param_data)
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 123, in extend
    if not elem_seq:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by cxm1995** [comment]
求助一下您

**Comment by cxm1995** [comment]
can u help me
